In [2]:
import numpy as np
array_1d = np.arange(10, 51)
print(array_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [3]:
array_3x3 = np.random.rand(3, 3)
print(array_3x3)

[[0.6569791  0.02360028 0.20529296]
 [0.41991164 0.53325129 0.22189352]
 [0.18191544 0.83352433 0.02732127]]


In [5]:
array_1d.shape

(41,)

In [6]:
array_1d.size

41

In [7]:
array_1d.dtype

dtype('int32')

In [8]:
array_1d + 5

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [9]:
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
array_2d_1 * array_2d_2 

array([[ 5, 12],
       [21, 32]])

In [13]:
array1=np.arange(1, 26).reshape(5, 5)
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
array1[0, :]

array([1, 2, 3, 4, 5])

In [15]:
array1[:, -1]

array([ 5, 10, 15, 20, 25])

In [16]:
array1[:3, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [20]:
random_array=np.random.randint(1, 101, size=10)
print(random_array)

[90 52 36 23 60 94 40 48 53 99]


In [21]:
random_array.max()

99

In [22]:
random_array.min()

23

In [23]:
mean_value = random_array.mean()
print(mean_value)
std_dev = random_array.std()
print(std_dev)

59.5
24.85256525994852


In [24]:
reshaped_array = np.arange(1, 13).reshape(3, 4)
print(reshaped_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
ones_matrix = np.ones((3, 3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
array_to_add=np.array([1, 2, 3])
print(array_to_add)

[1 2 3]


In [29]:
add=ones_matrix+array_to_add
print(add)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [30]:
random_integers = np.random.randint(1, 51, size=10)
print(random_integers)
divisible_by_5 = random_integers[random_integers % 5 == 0]
print(divisible_by_5)

[20 30 11  8 11  5  3  6 46 37]
[20 30  5]


In [31]:
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
np.dot(matrix_1, matrix_2)

array([[19, 22],
       [43, 50]])

In [33]:
array_4x4 = np.arange(1, 17).reshape(4, 4)
print(array_4x4)
diagonal_elements = array_4x4[np.arange(4), np.arange(4)]
print(diagonal_elements)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]


In [34]:
cd


C:\Users\CVR
